use serde::Deserialize;

#[allow(non_snake_case)]
#[derive(Deserialize, Debug, Clone)]
pub struct ClientServicePlan {
    pub servicePlanId: Option<usize>,
    pub servicePlanPeriodId: Option<usize>,
    pub activeFrom: Option<String>,
    pub activeTo: Option<String>,
    pub name: Option<String>,
    pub price: Option<f64>,
    pub note: Option<String>,
    pub invoicingStart: Option<String>,
    pub invoicingPeriodType: Option<usize>,
    pub invoicingPeriodStartDay: Option<usize>,
    pub nextInvoicingDayAdjustment: Option<f64>,
    pub invoicingProratedSeparately: Option<bool>,
    pub invoicingSeparately: Option<bool>,
    pub sendEmailsAutomatically: Option<bool>,
    pub useCreditAutomatically: Option<bool>,
    pub invoiceLabel: Option<String>,
    pub street1: Option<String>,
    pub street2: Option<String>,
    pub city: Option<String>,
    pub countryId: Option<usize>,
    pub stateId: Option<usize>,
    pub zipCode: Option<String>,
    pub addressGpsLat: Option<f64>,
    pub addressGpsLon: Option<f64>,
    pub contractId: Option<String>,
    pub contractLengthType: Option<usize>,
    pub minimumContractLengthMonths: Option<f64>,
    pub contractEndDate: Option<String>,
    pub discountType: Option<usize>,
    pub discountValue: Option<f64>,
    pub discountInvoiceLabel: Option<String>,
    pub discountFrom: Option<String>,
    pub discountTo: Option<String>,
    pub tax1Id: Option<usize>,
    pub tax2Id: Option<usize>,
    pub tax3Id: Option<usize>,
    pub id: Option<usize>,
    pub clientId: Option<usize>,
    pub status: Option<usize>,
    pub fccBlockId: Option<String>,
    pub hasIndividualPrice: Option<bool>,
    pub totalPrice: Option<f64>,
    pub servicePlanName: Option<String>,
    pub servicePlanPrice: Option<f64>,
    pub servicePlanPeriod: Option<f64>,
    pub downloadSpeed: Option<f64>,
    pub uploadSpeed: Option<f64>,
    pub ipRanges: Option<Vec<String>>,
    pub currencyCode: Option<String>,
    pub hasOutage: Option<bool>,
    pub lastInvoicedDate: Option<String>,
    pub unmsClientSiteId: Option<String>,
}
